title: Temi Oloyede
url: "https://teimilola.github.io/"
baseurl: ""

rss: rss

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tracking_id: UA-156013933-1

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

theme: jekyll-theme-minimal

sass:
    style: compressed
    sass_dir: _sass
    

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Blog Posts
